// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMaWeYr94KLAKBswMvggrbCdmtLyOhbo',
    appId: '1:746981007191:web:df619a508e871c42dce812',
    messagingSenderId: '746981007191',
    projectId: 'my-cycles-4me',
    authDomain: 'my-cycles-4me.firebaseapp.com',
    storageBucket: 'my-cycles-4me.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGOVcG-RomfRkLm0HvsoVMWMdn0BtWYC8',
    appId: '1:746981007191:android:320dfb10e4e986b7dce812',
    messagingSenderId: '746981007191',
    projectId: 'my-cycles-4me',
    storageBucket: 'my-cycles-4me.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMaWeYr94KLAKBswMvggrbCdmtLyOhbo',
    appId: '1:746981007191:web:2fee791a28680b45dce812',
    messagingSenderId: '746981007191',
    projectId: 'my-cycles-4me',
    authDomain: 'my-cycles-4me.firebaseapp.com',
    storageBucket: 'my-cycles-4me.appspot.com',
  );
}
